[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.cursor]
cursor = "#d65d0e"
text = "#1d2021"

[colors.dim]
black = "#665c54"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#cc241d"
white = "#a89984"
yellow = "#fabd2f"

[colors.hints.end]
background = "#d79921"
foreground = "#1d2021"

[colors.hints.start]
background = "#fabd2f"
foreground = "#1d2021"

[colors.normal]
black = "#1d2021"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
bright_foreground = "#ebdbb2"
dim_foreground = "#a89984"
foreground = "#ebdbb2"

[colors.search.focused_match]
background = "#98971a"
foreground = "#1d2021"

[colors.footer_bar]
background = "#d79921"
foreground = "#1d2021"

[colors.search.matches]
background = "#d79921"
foreground = "#1d2021"

[colors.selection]
background = "#3c3836"
text = "#fbf1c7"

[colors.vi_mode_cursor]
cursor = "#d79921"
text = "#1d2021"
